### ISSUE TITLE
transaction builder - Transaction object constructor undefines groupID value

### ISSUE THREAD

**Issue by purestaketdb** [algorand/js-algorand-sdk#241] opened 2020-11-09 21:06 UTC
In the SDK it is perfectly valid to assemble a transaction and have it signed using the `signTransaction` function in main.js. This works fine. 

However, in `signTransaction` the transaction values are sent through to the transaction builder andTransaction object in transaction.js. In the last line of that objects constructor, it declares and undefines the group ID value, even if it is populated already. 

```JS
        // say we are aware of groups
        this.group = undefined;

```

This is incorrect, it should first check if the value exists before overwriting it.

**Comment by jasonpaulos** [comment] 2020-11-10 13:39
Hi @purestaketdb, to our knowledge setting group to undefined in the Transaction constructor should not cause any problems since that constructor does not take group as an input. Could you share a small example that reproduces the problem you are seeing?

**Comment by purestaketdb** [comment] 2020-11-10 14:06
You are correct , if groupID is defined on an object sent in through signTransaction it will strip the groupID off immediately in the constructor - so the first bug to fix is actually including that value in the constructor and the second to not undefine it.

**Comment by jasonpaulos** [comment] 2020-11-13 16:48
Can you provide sample code where this is an issue? I'm not aware of a use case that would set the groupID before the transaction object is passed to the Transaction constructor.

**Comment by purestaketdb** [comment] 2020-11-13 17:39
On your example page - https://developer.algorand.org/docs/features/atomic_transfers/ -it demonstrates this as the first use case. 

Our specific use case is transferring the data for a transaction (not a transaction builder object) through to an extension over the built in chrome messaging API from a web application. To do that, the dApp builds the transactions and obtains the group ID, then sends the data across in a string representation, where it is presented to the user then signed. 

In the signing operation the transaction is cast through the transaction builder, where the group ID, if present, is removed. 

We are trying to work around this now by casting the data into the object ourselves and then appending the groupID afterwards and will be publishing this in the next week or so.

**Comment by jasonpaulos** [comment] 2020-11-19 20:24
Hi @purestaketdb, I think your use case might be better supported by using `encodeUnsignedTransaction` & `decodeUnsignedTransaction` (introduced in 1.8.0) instead of the Transaction constructor:

```javascript
const myTxn =  // a Transaction object
const encodedTxn = algosdk.encodeUnsignedTransaction(myTxn); // a Uint8Array

// transmit encodedTxn over messaging API
// if the messaging API does not support Uint8Arrays, then base64 encode & decode it

const myTxnDecoded = algosdk.decodeUnsignedTransaction(encodedTxn); // a Transaction object
```

The Transaction constructor was never designed to deserialized an object, and we already have well tested methods to do this. Let me know if this approach would work for you.

**Comment by purestaketdb** [comment] 2020-11-19 20:32
What we ended up doing is using the Transaction constructor ourselves and then updating the groupId afterwards. We'll take a look at the two new functions for our upcoming releases, thanks for pointing them out. 

I still don't agree that the constructor should drop the groupId if it's provided, is there a reason it is excluded? The last action is to create that property and set it as undefined so it could just be created in the constructor with an undefined default.

**Comment by jasonpaulos** [comment] 2020-11-20 20:20
I think the reason it's excluded is because group is a generated property of a transaction, like signature. The purpose of the Transaction constructor is to create _new_ transactions and new transactions don't have generated properties yet. In the future we may have even more generated properties, and the Transaction constructor isn't really the place for them to be assigned.

If you want to serialize and deserialize transactions in a way that includes generated properties, `encodeUnsignedTransaction` and `decodeUnsignedTransaction` are meant for that. As a bonus, the encoding they use is standard across the Algorand ecosystem, so other SDKs and goal can read & debug them.

I suppose the situation is complicated by the fact that we recently started automatically converting raw objects to Transactions if they're passed into `signTransaction` and `assignGroupID` for convenience. We could definitely add more documentation about this process, and in the future we may even want to deprecate the use of raw transaction objects entirely to really decouple transaction creation and use.

**Comment by jasonpaulos** [comment] 2021-02-24 21:58
Closing this because I believe there's a solution. Feel free to reopen if needed.

**Closed by jasonpaulos** 2021-02-24 21:58 UTC
Labels: FDE
