### ISSUE TITLE
Using tealdbg debug with SDK's DryRunRequest

### ISSUE THREAD

**Issue by ratik21** [algorand/js-algorand-sdk#374] opened 2021-06-11 10:23 UTC
Hi, i am not able to use `tealdbg debug` with SDK's [DryRunRequest](https://algorand.github.io/js-algorand-sdk/classes/modelsv2.dryrunrequest.html).

What i want is:
+ create a dryrunrequest object
+ dump the sdk request object to a file (say `dump.tx`)
+ use `tealdbg debug -d dump.tx`

What i am doing (followed [this](https://github.com/algorand/docs/blob/master/examples/smart_contracts/v2/javascript/dryrunDebugging.js#L132) example):
```js
const  tx = algosdk.makePaymentTxnWithSuggestedParams({..});
const dr = new algosdk.modelsv2.DryrunRequest({
  txns: [ { txn: tx, lsig: lsig } ],
  sources: undefined
});
await writeToFile(JSON.stringify(dr.get_obj_for_encoding(), null, 2), "sdk-dump.tx"); // attached sdk-dump.tx file
``` 
now when i use `tealdbg debug -d dump.tx`, i get the following error:
```bash
2021/06/11 15:39:39 Debug error: json decode error [pos 808]: invalid syntax for integer: type
```

When trying to create the same dump using goal using below, `tealdbg debug -d goal-dump.tx` works as expected:
```
goal clerk send -a=20 --to=<to_addr> --from-program=contract.teal --out=goal-dump.tx --dryrun-dump // attached goal-dump.tx file
```
There are differences in the sdk (with sdk there are buffers in tx encoded object) & goal dryrun dumps. Could that be the issue?

files:
[goal-dump.tx](https://github.com/algorand/js-algorand-sdk/files/6637662/goal-dump.txt)
[sdk-dump.tx](https://github.com/algorand/js-algorand-sdk/files/6637663/sdk-dump.txt)

**Comment by robert-zaremba** [comment] 2021-07-09 08:01
What's the expected ETA? This issue is blocking us.

**Comment by robert-zaremba** [comment] 2021-07-09 08:03
Is this solved by https://github.com/algorand/js-algorand-sdk/pull/399 ?

**Comment by jasonpaulos** [comment] 2021-07-09 17:16
This is partially solved by #399. By that I mean you are now able to properly serialize the dryrun request as a msgpack object, but the code above that serializes it as JSON still won't work.

You'll have to install the latest version from develop to get the fix from #399, e.g. `npm i git://github.com/algorand/js-algorand-sdk`.

Then, you can do this instead:
```javascript
await writeToFile(algosdk.encodeObj(dr.get_obj_for_encoding(true)), "sdk-dump.msgp");
```

To examine the contents of the msgpack dump, you can do `msgpacktool -d < sdk-dump-fixed.msgp`.

And of course you can still use this with the debugger with `tealdbg debug -d sdk-dump-fixed.msgp`.

Let me know if there are any issues with this.

**Comment by ratik21** [comment] 2021-07-12 11:21
@jasonpaulos thanks, the above suggestion is working and i'm able to use the debugger with `sdk-dump.msgp` (for lsig).

However, when i am trying to the same with a stateful application call transaction, i am getting:
```
2021/07/12 16:47:33 Using proto: https://github.com/algorandfoundation/specs/tree/d050b3cade6d5c664df8bd729bf219f179812595
2021/07/12 16:47:33 Debug error: all 1 program(s) failed in less than a second, invocation error?
```
I constructed the request same as in [this comment](https://github.com/algorand/js-algorand-sdk/issues/373#issue-918205426).

**Comment by jasonpaulos** [comment] 2021-07-12 23:51
That error implies the encoding is ok, but something else is wrong. Can you provide the `sdk-dump.msgp` file you are using? I'll take a look.

**Comment by ratik21** [comment] 2021-07-14 22:09
I have provided an executable script to reproduce this in [this](https://github.com/algorand/js-algorand-sdk/issues/373#issuecomment-880241411) comment. Attaching `sdk-dump.msgp` (encoded in zip) separately here as well. 
[sdk-dump.zip](https://github.com/algorand/js-algorand-sdk/files/6819173/sdk-dump.zip)

**Comment by jasonpaulos** [comment] 2021-07-21 23:14
I could not reproduce the issue with the files you provided. Based on our conversation from discord, I believe the problem you're seeing is because yarn has problems installing packages from github that require build steps. Closing for now, feel free to reopen if you can reproduce using the latest commit from develop.

**Closed by jasonpaulos** 2021-07-21 23:14 UTC
Labels: Team Scytale, bug

**Comment by jasonpaulos** [comment] 2021-07-26 17:24
The issue ended up being that the response from the `getApplicationByID` algod call cannot be used as an input to the `DryrunRequest` constructor; you have to create a new `algosdk.modelsv2.Application`. Here's what ended up working:

```javascript
  const app = await algodClient.getApplicationByID(appInfo['application-index']).do();
  
  const globalStateSchema = new algosdk.modelsv2.ApplicationStateSchema(app.params['global-state-schema']['num-uint'], app.params['global-state-schema']['num-byte-slice']);
  const localStateSchema = new algosdk.modelsv2.ApplicationStateSchema(app.params['local-state-schema']['num-uint'], app.params['local-state-schema']['num-byte-slice']);

  const globalState = (app.params['global-state'] || []).map(({ key, value }) => (
    new algosdk.modelsv2.TealKeyValue(key, new algosdk.modelsv2.TealValue(value.type, value.bytes, value.uint))
  ));
  
  const appParams = new algosdk.modelsv2.ApplicationParams({
    approvalProgram: app.params['approval-program'],
    clearStateProgram: app.params['clear-state-program'],
    creator: app.params.creator,
    globalState,
    globalStateSchema,
    localStateSchema,
    extraProgramPages: app.params['extra-program-pages'],
  });
  const appForDryRun = new algosdk.modelsv2.Application(app.id, appParams);
  
  const dr = new algosdk.modelsv2.DryrunRequest({
    apps: [appForDryRun],
    txns: [decodedTxn],
    sources: undefined
  });
```
