### ISSUE TITLE
Error while importing in Vite (SvelteKit) 

### ISSUE THREAD

**Issue by NoelJacob** [algorand/js-algorand-sdk#398] opened 2021-07-07 19:08 UTC

**Comment by jasonpaulos** [comment] 2021-07-08 16:09
@NoelJacob please give more context for this issue

**Comment by NoelJacob** [comment] 2021-07-08 17:05
I did the following commands
```
pnpm init svelte@next
pnpm install
pnpm install algosdk
pnpm run dev
```
Then I get:
![image](https://user-images.githubusercontent.com/54862022/124960013-7a077980-e039-11eb-887a-6bbc6fc9b948.png)

I could not add any kind of nodejs polyfills.

I tried few rollup polyfill plugins with vite and also changing vite configurations `kit.vite.optimiseDeps.exclude` and `kit.vite.ssr.noExternal` but all this throws different errors.
Maybe this is solvable by somehow configuring `@rollup/plugin-node-resolve` in vite plugins?

The library works perfectly with Webpack with `node-polyfill-webpack-plugin`.
I also could not getting it working with Snowpack or Rollup, although I didn't change their configs much.

My [repo ](https://github.com/NoelJacob/algod-test)with the error.

**Comment by jasonpaulos** [comment] 2021-07-08 20:36
I'm not familiar with vite, but you will need to add two polyfills for node packages in order for this package to work: `buffer` and `path-browserify`. You can see where these packages are declared in our webpack config here: https://github.com/algorand/js-algorand-sdk/blob/develop/webpack.config.js. Note that this package expects `Buffer` to be a global variable, so just installing the `buffer` package won't be enough.

**Comment by MrJackdaw** [comment] 2021-07-25 00:22
> I'm not familiar with vite, but you will need to add two polyfills for node packages in order for this package to work: `buffer` and `path-browserify`. You can see where these packages are declared in our webpack config here: https://github.com/algorand/js-algorand-sdk/blob/develop/webpack.config.js. Note that this package expects `Buffer` to be a global variable, so just installing the `buffer` package won't be enough.

Hello @jasonpaulos: I also ran into this error as well (while working with [Reach](https://docs.reach.sh). You mentioned being unfamiliar with Vite, and so I hope the following either provides clues or helps with suggestions.

### Background

I previously encountered an issue where `process` was undefined (vite uses `import.meta. ...`). Vite's config has a `define` section for adding global constants: adding `"process.env": someCustomFallbackObject` there worked. 

A few `Reach-sh` library updates later, this (Buffer) problem surfaced.

### Solution Attempts
1. I installed the `buffer` package and added it as a global in the config file. 
```javascript
import { Buffer } from 'buffer';

export default defineConfig({
  plugins: [ ... ],
  define: {
    "process.env": env,
  },
 ...
})
```

This moved the error message from OP's original report to:

```
Uncaught TypeError: Cannot read property 'from' of undefined
```

<img width="579" alt="Screen Shot 2021-07-24 at 5 08 21 PM" src="https://user-images.githubusercontent.com/6107109/126883730-b36629cf-39a4-4748-adc9-a599990b5f02.png">

After finding this thread, I added the following packages (`buffer ^6.0.3` was already installed): 

```json
   "path-browserify": "^1.0.1",
```

And the following to my [`vite.config.js` file](https://vitejs.dev/config/#configuring-vite):

```
resolve: {
    alias: {
      ...
      path: require.resolve("path-browserify")
    },
```

The error message is unchanged. I hunted through `node_modules` and my best guess is that it still can't find `Buffer` (since I see references to `Buffer.from( ... )`. 

Any advice? Cheers for taking the time.

**Comment by jdtzmn** [comment] 2021-07-26 21:00
Knowing nothing about Vite either, wouldn't you have to include the imported `Buffer` in your `defineConfig`?

```js
import { Buffer } from 'buffer';

export default defineConfig({
  plugins: [ ... ],
  define: {
    "process.env": env,
    "Buffer": Buffer // <-- This line
  },
 ...
})
```

You mentioned that you imported it, but it didn't appear in your code sample 🤷‍♂️ .

**Comment by MrJackdaw** [comment] 2021-07-26 21:34
> Knowing nothing about Vite either, wouldn't you have to include the imported `Buffer` in your `defineConfig`?
> 
> ```js
> import { Buffer } from 'buffer';
> 
> export default defineConfig({
>   plugins: [ ... ],
>   define: {
>     "process.env": env,
>     "Buffer": Buffer // <-- This line
>   },
>  ...
> })
> ```
> 
> You mentioned that you imported it, but it didn't appear in your code sample 🤷‍♂️ .

Cheers for the response; I omitted it since the snippets are entirely demonstrative: it was indeed included in the file, which changes the error from 

```
'Buffer' is undefined
```
to
```
Uncaught TypeError: Cannot read property 'from' of undefined
```

Which means the `Buffer` import is recognized (using the "global" technique outlined above), but the failure persists around the use of `Buffer` as a global variable in the actual packages.

**Comment by jdtzmn** [comment] 2021-07-27 13:54
@MrJackdaw two things to try:

1. Try putting the `Buffer` override in the `alias` section (like with `path-browserify`) instead of the `define` section.
2. Try adding a slash to the end of the `buffer` import, as described in the [buffer package's usage section](https://www.npmjs.com/package/buffer#usage).

**Comment by MrJackdaw** [comment] 2021-07-27 16:43
@jdtzmn Thanks for the suggestion. I tried your suggestion (and a few variations) -- and they ultimately confirmed my suspicion: "buffer" is getting defined, but isn't getting consumed (possibly due to how vite bundles the dev environment).

### What was done

1. I removed my initial import and replaced it with 
```javascript
const Buffer = require("buffer/");
```
and left `Buffer` in the `define` global space: no change to error
2. I removed the `Buffer` from the global name space and added it to the `resolve` space:
```javascript
   ...
   resolve: {
      alias: {
         ...
         Buffer: require("buffer/")
      }
   }
```
which changed the error back to `Buffer is not defined`
2. I updated the `Buffer` alias to
```javascript
   ...
   resolve: {
      alias: {
         ...
         Buffer: require.resolve("buffer/")
      }
   }
```
which changed the error to a slightly more descriptive error (with the same stack trace in my original post):
```
Uncaught TypeError: define_Buffer_default.from is not a function
```

It would seem that both `config.resolve.alias` and `config.define` can be used for _some_ types of global variables--or their effects are somewhat interchangeable in this case. Vite recommends the use of plugins for advanced custom resolution: I tried a few but never got past the "undefined `from`" error. 

Hope this gives more insight; cheers again for the help

**Comment by JoviDeCroock** [comment] 2021-07-30 08:21
Hey all,

Generally this would be fixed by using a polyfill for the `node.js Buffer` implementation, this can be done the following way:

`npm i --save buffer` or `yarn add buffer` and in your entry-point of vite doing:

```
import { Buffer } from 'buffer'
globalThis.Buffer = Buffer
```

This will ensure that even if you use `SSR` it won't try to assert window being present

**Comment by MrJackdaw** [comment] 2021-08-07 19:21
> Hey all,
> 
> Generally this would be fixed by using a polyfill for the `node.js Buffer` implementation, this can be done the following way:
> 
> `npm i --save buffer` or `yarn add buffer` and in your entry-point of vite doing:
> 
> ```js
> import { Buffer } from 'buffer'
> globalThis.Buffer = Buffer
> ```
> 
> This will ensure that even if you use `SSR` it won't try to assert window being present. To have this work this needs to be your entry-point before ever importing this library.
> 
> Alternatively you can use `rollup-plugin-node-polyfills` in your `vite.config` by inserting it into the [inputOptions](https://github.com/vitejs/vite/blob/2893a4149bbf2baf8a895a12ee6548148481a7bf/src/node/config.ts#L274)

Hey @JoviDeCroock, thanks for taking the time. Unfortunately, `rollup-plugin-node-polyfills` was one of the first solutions I tried: there's no effect using the `rollupInputOptions`, since that is a subset of instructions for the build output. 

### Summary of (unsuccessful) attempts so far

- Using [`nodePolyfill`](https://github.com/snowpackjs/rollup-plugin-polyfill-node)
   - This did trigger an environment change, since experimental Vue3 features stopped working. 
   - Sadly, the `Buffer` issue was unresolved by the change
- Replaced `buffer` with [`safe-buffer`](https://www.npmjs.com/package/safe-buffer) (made by the same person it seems)
   - This had the same effect as before: 
      -  Misconfiguration (i.e. failing to define, or properly define `buffer`) will cause a compile error related to `buffer` imports
      - Correct configuration (defining both `buffer` _and_ its `Buffer` class) results in the `Buffer.from is not a function` error
- Tried suggestions from [this comment](https://github.com/vitejs/vite/discussions/3126#discussioncomment-655531) in a Vite github issue. 
   - Tried "excluding" both `algosdk` (used under the hood by `@reach-sh/stdlib`) as well as the Reach library from dependency optimization
   - Tried including both (of the above) to force dependency optimization by Vite

Is there ... something I'm missing? Or is there _any chance in hell_ that the sdk will switch over to an explicit polyfill (v.s. global reference) for its `Buffer` usage?

**Comment by andsav** [comment] 2021-12-20 08:34
This is what is working for me:

1. `yarn add buffer`

2. Replace `window.Buffer` when your point of entry mounts (e.g. `__layour.svelte`):

```typescript
import { browser } from '$app/env';  
import { onMount } from 'svelte';

onMount(async () => {
  if (browser) {
    const { Buffer } = await import('buffer')
    window.Buffer = Buffer
  }
})
```

3. Load the component importing `algosdk` dynamically. Example:

```svelte
<script lang="ts">
import { onMount } from 'svelte';
let Wallet;

onMount(() => {
  if (Wallet) {
    return;
  }

  import('$lib/Wallet.svelte').then(module => {
    Wallet = module.default;
  )}
});
</script>

{#if Wallet}
  <svelte:component this={Wallet} />
{/if}
```

**Comment by pnapoliJC** [comment] 2022-02-09 19:14
@MrJackdaw 

I finally found the fix for this issue, I'll keep it short and simple, install the following packages:

`yarn add @esbuild-plugins/node-globals-polyfill path-browserify`

Then in vite.config.js make sure you add:

```js
import { defineConfig } from 'vite'
import Vue from '@vitejs/plugin-vue'

import NodeGlobalsPolyfillPlugin from '@esbuild-plugins/node-globals-polyfill'

export default defineConfig({
  resolve: {
    alias: {
      path: 'path-browserify',
    },
  },
  optimizeDeps: {
    esbuildOptions: {
      // Node.js global to browser globalThis
      define: {
          global: 'globalThis'
      },
      // Enable esbuild polyfill plugins
      plugins: [
          NodeGlobalsPolyfillPlugin({
              buffer: true
          })
      ]
    }
  },
})
```

The key here was the package `@esbuild-plugins/node-globals-polyfill`, which later brought the `path` issue, which was resolved adding it in the alias, and installing `path-browserify`

After this, `algosdk` is now working fine. Hope it helps!

**Comment by fionnachan** [comment] 2022-02-10 04:50
Some installation instructions for Vite were added to the FAQ page if anyone new is looking
https://github.com/algorand/js-algorand-sdk/blob/develop/FAQ.md#it-says-error-cant-resolve-in-the-sdk

#### Vite projects

With Vite, you would see:

```
Uncaught ReferenceError: Buffer is not defined
```

You will have to install `buffer` and `path-browserify` as dependencies.

In `vite.config.js`, specify:

```js
resolve: {
  alias: {
    path: 'path-browserify';
  }
}
```

In `index.html`, add the following:

```html
<script type="module">
  import { Buffer } from 'buffer';
  window.Buffer = Buffer;
</script>
```

To utilize the Buffer polyfill in production builds, in `vite.config.js`, add:

```js
import inject from '@rollup/plugin-inject';
export default defineConfig({
  ...,
  build: {
    rollupOptions: {
      plugins: [inject({ Buffer: ['buffer', 'Buffer'] })],
    },
  },
  ...
});
```

**Comment by RyanPrentiss** [comment] 2022-10-30 22:36
This is what resolved all the issues for me.

_vite.config.js_

```
import { NodeGlobalsPolyfillPlugin } from '@esbuild-plugins/node-globals-polyfill'
import { NodeModulesPolyfillPlugin } from '@esbuild-plugins/node-modules-polyfill'

export default defineConfig({
    optimizeDeps: {
        esbuildOptions: {
            plugins: [NodeGlobalsPolyfillPlugin(), NodeModulesPolyfillPlugin()],
        },
    },
})
```

**Comment by vmanot** [comment] 2023-01-09 20:11
[This solved the problem in my case.](https://github.com/sveltejs/vite-plugin-svelte/issues/23#issuecomment-830871578)

> closing here as the original issue can be solved with relative configFile option added in 1.0.0-next.8: `svelte({configFile:"../svelte.config.js"})`

**Comment by spencercap** [comment] 2023-09-19 21:47
we use algosdk in vue + vite projects frequently! 

in truth, it hasnt always been so straight forward getting algosdk to work in this setup so we made a helpful pkg [`algonautjs`](https://www.npmjs.com/package/@thencc/algonautjs) that is ESM native and wraps algosdk. 

---

we also just open-sourced a wallet connection handler lib that supports most all algorand wallets, which you can find here: [`any-wallet`](https://github.com/thencc/any-wallet).

**Comment by jasonpaulos** [comment] 2023-09-20 14:11
To my knowledge, over the past few months this SDK has eliminated the need for external configuration, so I'm closing this. If someone is still having issues, please comment. It's in our best interest to make using this SDK as easy as possible.

**Closed by jasonpaulos** 2023-09-20 14:11 UTC
Labels: external contribution
