### ISSUE TITLE
Close to amount not in transaction response

### ISSUE THREAD

**Issue by rfustino** [algorand/js-algorand-sdk#395] opened 2021-07-01 17:55 UTC
When the close to account is specified in the pay transaction call, the transaction response does not include the close to amount like the Java SDK. This is inconsistent and needed, otherwise it is more difficult to determine from the response how much actually went to the the close to account. running 1.10.0 of the js sdk. Repo code below.

```
const algosdk = require('algosdk');
const readline = require("readline");
const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

// Create an account and add funds to it. Copy the address off
// The Algorand TestNet Dispenser is located here: 
// https://dispenser.testnet.aws.algodev.network/

const createAccount = async function (){
    try{
  
        const myaccount = algosdk.generateAccount();
        console.log("My Account Address = " + myaccount.addr);
        let account_mnemonic = algosdk.secretKeyToMnemonic(myaccount.sk);
        console.log("Account Mnemonic = "+ account_mnemonic);
        console.log("Account created. Save off Mnemonic and address");
        console.log("Add funds to account using the TestNet Dispenser at https://dispenser.testnet.aws.algodev.network/ ");
        console.log('Press ENTER after dispensing funds');
        rl.on('line', (input) => {
            console.log(`Continuing: ${input}`);
            rl.close();
          });
        return myaccount;
    }
    catch (err) {
        console.log("err", err);
    }
};

/**
 * Wait until the transaction is confirmed or rejected, or until 'timeout'
 * number of rounds have passed.
 * @param {algosdk.Algodv2} algodClient the Algod V2 client
 * @param {string} txId the transaction ID to wait for
 * @param {number} timeout maximum number of rounds to wait
 * @return {Promise<*>} pending transaction information
 * @throws Throws an error if the transaction is not confirmed or rejected in the next timeout rounds
 */
 const waitForConfirmation = async function (algodClient, txId, timeout) {
    if (algodClient == null || txId == null || timeout < 0) {
        throw new Error("Bad arguments");
    }

    const status = (await algodClient.status().do());
    if (status === undefined) {
        throw new Error("Unable to get node status");
    }

    const startround = status["last-round"] + 1;
    let currentround = startround;

    while (currentround < (startround + timeout)) {
        const pendingInfo = await algodClient.pendingTransactionInformation(txId).do();
        if (pendingInfo !== undefined) {
            if (pendingInfo["confirmed-round"] !== null && pendingInfo["confirmed-round"] > 0) {
                //Got the completed Transaction
                return pendingInfo;
            } else {
                if (pendingInfo["pool-error"] != null && pendingInfo["pool-error"].length > 0) {
                    // If there was a pool error, then the transaction has been rejected!
                    throw new Error("Transaction " + txId + " rejected - pool error: " + pendingInfo["pool-error"]);
                }
            }
        }
        await algodClient.statusAfterBlock(currentround).do();
        currentround++;
    }
    throw new Error("Transaction " + txId + " not confirmed after " + timeout + " rounds!");
};
async function firstTransaction(Account) {

    try {
        let myAccount = await createAccount();
        console.log("My address: %s", myAccount.addr);
        console.log("My passphrase: " + algosdk.secretKeyToMnemonic(myAccount.sk));


        // Connect your client
        const algodToken = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
        const algodServer = "http://localhost";
        const algodPort = 4001;
        // const algodToken = '';
        // const algodServer = 'https://testnet.algoexplorerapi.io';
        // const algodPort = '';
        let algodClient = new algosdk.Algodv2(algodToken, algodServer, algodPort);

        //Check your balance
        let accountInfo = await algodClient.accountInformation(myAccount.addr).do();
        console.log("Account balance: %d microAlgos", accountInfo.amount);

        // Construct the transaction
        let params = await algodClient.getTransactionParams().do();
        // comment out the next two lines to use suggested fee
        params.fee = 1000;
        params.flatFee = true;

        // receiver defined as TestNet faucet address 
        const receiver = "HZ57J3K46JIJXILONBBZOHX6BKPXEM2VVXNRFSUED6DKFD5ZD24PMJ3MVA";
        const enc = new TextEncoder();
        const note = enc.encode("Hello World");

        let txn = algosdk.makePaymentTxnWithSuggestedParams(myAccount.addr, receiver, 1000000, receiver, note, params);

        // Sign the transaction
        let signedTxn = txn.signTxn(myAccount.sk);
        let txId = txn.txID().toString();
        console.log("Signed transaction with txID: %s", txId);

        // Submit the transaction
        await algodClient.sendRawTransaction(signedTxn).do();

        // Wait for confirmation
        let confirmedTxn = await waitForConfirmation(algodClient, txId, 4);
        //Get the completed Transaction
        console.log("Transaction " + txId + " confirmed in round " + confirmedTxn["confirmed-round"]);
        let mytxinfo = JSON.stringify(confirmedTxn.txn.txn, undefined, 2);
        console.log("Transaction information: %o", mytxinfo);
        var string = new TextDecoder().decode(confirmedTxn.txn.txn.note);
        console.log("Note field: ", string);
        accountInfo = await algodClient.accountInformation(myAccount.addr).do();
        console.log("Transaction Amount: %d microAlgos", confirmedTxn.txn.txn.amt);        
        console.log("Transaction Fee: %d microAlgos", confirmedTxn.txn.txn.fee);
        console.log("Close To Amount ????: %d microAlgos", confirmedTxn.txn.txn.close);
        console.log("Account balance: %d microAlgos", accountInfo.amount);
    }
    catch (err) {
        console.log("err", err);
    }
};


firstTransaction();
```

**Comment by jasonpaulos** [comment] 2021-07-01 18:22
This SDK directly returns the response from algod, so I'm pretty sure the close to amount should be in there.

According to the [REST API docs](https://developer.algorand.org/docs/reference/rest-apis/algod/v2/#get-v2transactionspendingtxid), the field is called `closing-amount` and it should be available as `confirmedTxn["closing-amount"]` in your example. Let me know if this is not the case.

**Comment by chaihoang** [comment] 2021-07-07 19:25
@rfustino Can you confirm whether Jason's comment is correct? Thanks.

**Comment by jasonpaulos** [comment] 2021-07-26 16:16
Closing this because I believe it's not an issue, but @rfustino please reopen if you can't get my above suggestion to work.

**Closed by jasonpaulos** 2021-07-26 16:16 UTC
Labels: Team Scytale
