### ISSUE TITLE
Update the webapp example to V2

### ISSUE THREAD

**Issue by rfustino** [algorand/js-algorand-sdk#257] opened 2020-12-09 15:52 UTC
The webapp sample needs to be updated to V2 and potentially using indexer for the search game functions. https://github.com/algorand/js-algorand-sdk/tree/develop/examples/webapp

**Comment by ian-algorand** [comment] 2020-12-21 18:38
This is a duplicate of another issue we have @rfustino

**Closed by ian-algorand** 2020-12-21 18:38 UTC
