### ISSUE TITLE
Add the ability to convert between Buffer and Transaction object

### ISSUE THREAD

**Issue by EvanJRichard** [algorand/js-algorand-sdk#176] opened 2020-06-19 17:08 UTC
In pseudocode, the way to make a signed transaction or logic sig and write it to file, and then read it back in from file, would be:
```
let txn_or_lsig_or_etc = // we'll skip making the proper object
let writeBytes = algosdk.encodeObj(txn_or_lsig_or_etc.to_obj_for_encoding();
writeToFile(filename, writeBytes);
//[...]
let readBytes = readFile(filename);
let objDict = algosdk.decodeObj(readBytes);
let txn = Transaction.from_obj_for_encoding(objDict); // or equivalent for lsig, or multisig, etc.
```
But the final function, `from_obj_for_encoding`, is not exposed by SDK. This blocks some user use cases. So, add `toByte` and `fromByte` functions to convert between `Buffer`s and `Transaction`s

**Comment by ian-algorand** [comment] 2020-07-13 17:16
duplicate of https://github.com/algorand/js-algorand-sdk/issues/114

**Closed** 2020-09-29 13:42 UTC
Labels: FDE, bug
